package def.dom;

import def.js.Object;
import def.js.StringTypes;
import def.js.StringTypes.DeviceMotionEvent;
import def.js.StringTypes.DeviceOrientationEvent;
import def.js.StringTypes.DragEvent;
import def.js.StringTypes.ErrorEvent;
import def.js.StringTypes.Event;
import def.js.StringTypes.Events;
import def.js.StringTypes.FocusEvent;
import def.js.StringTypes.LongRunningScriptDetectedEvent;
import def.js.StringTypes.MessageEvent;
import def.js.StringTypes.MouseEvents;
import def.js.StringTypes.MouseWheelEvent;
import def.js.StringTypes.MutationEvent;
import def.js.StringTypes.MutationEvents;
import def.js.StringTypes.NavigationEventWithReferrer;
import def.js.StringTypes.OfflineAudioCompletionEvent;
import def.js.StringTypes.PageTransitionEvent;
import def.js.StringTypes.PopStateEvent;
import def.js.StringTypes.SVGZoomEvents;
import def.js.StringTypes.StorageEvent;
import def.js.StringTypes.TransitionEvent;
import def.js.StringTypes.UIEvents;
import def.js.StringTypes.WebGLContextEvent;

@jsweet.lang.Interface
public abstract class DocumentEvent extends def.js.Object {
    native public AnimationEvent createEvent(def.js.StringTypes.AnimationEvent eventInterface);
    native public AriaRequestEvent createEvent(def.js.StringTypes.AriaRequestEvent eventInterface);
    native public AudioProcessingEvent createEvent(def.js.StringTypes.AudioProcessingEvent eventInterface);
    native public BeforeUnloadEvent createEvent(def.js.StringTypes.BeforeUnloadEvent eventInterface);
    native public ClipboardEvent createEvent(def.js.StringTypes.ClipboardEvent eventInterface);
    native public CloseEvent createEvent(def.js.StringTypes.CloseEvent eventInterface);
    native public CommandEvent createEvent(def.js.StringTypes.CommandEvent eventInterface);
    native public CompositionEvent createEvent(def.js.StringTypes.CompositionEvent eventInterface);
    native public CustomEvent createEvent(def.js.StringTypes.CustomEvent eventInterface);
    native public DeviceMotionEvent createEvent(def.js.StringTypes.DeviceMotionEvent eventInterface);
    native public DeviceOrientationEvent createEvent(def.js.StringTypes.DeviceOrientationEvent eventInterface);
    native public DragEvent createEvent(def.js.StringTypes.DragEvent eventInterface);
    native public ErrorEvent createEvent(def.js.StringTypes.ErrorEvent eventInterface);
    native public Event createEvent(def.js.StringTypes.Event eventInterface);
    native public Event createEvent(def.js.StringTypes.Events eventInterface);
    native public FocusEvent createEvent(def.js.StringTypes.FocusEvent eventInterface);
    native public GamepadEvent createEvent(def.js.StringTypes.GamepadEvent eventInterface);
    native public HashChangeEvent createEvent(def.js.StringTypes.HashChangeEvent eventInterface);
    native public IDBVersionChangeEvent createEvent(def.js.StringTypes.IDBVersionChangeEvent eventInterface);
    native public KeyboardEvent createEvent(def.js.StringTypes.KeyboardEvent eventInterface);
    native public LongRunningScriptDetectedEvent createEvent(def.js.StringTypes.LongRunningScriptDetectedEvent eventInterface);
    native public MSGestureEvent createEvent(def.js.StringTypes.MSGestureEvent eventInterface);
    native public MSManipulationEvent createEvent(def.js.StringTypes.MSManipulationEvent eventInterface);
    native public MSMediaKeyMessageEvent createEvent(def.js.StringTypes.MSMediaKeyMessageEvent eventInterface);
    native public MSMediaKeyNeededEvent createEvent(def.js.StringTypes.MSMediaKeyNeededEvent eventInterface);
    native public MSPointerEvent createEvent(def.js.StringTypes.MSPointerEvent eventInterface);
    native public MSSiteModeEvent createEvent(def.js.StringTypes.MSSiteModeEvent eventInterface);
    native public MessageEvent createEvent(def.js.StringTypes.MessageEvent eventInterface);
    native public MouseEvent createEvent(def.js.StringTypes.MouseEvent eventInterface);
    native public MouseEvent createEvent(def.js.StringTypes.MouseEvents eventInterface);
    native public MouseWheelEvent createEvent(def.js.StringTypes.MouseWheelEvent eventInterface);
    native public MutationEvent createEvent(def.js.StringTypes.MutationEvent eventInterface);
    native public MutationEvent createEvent(def.js.StringTypes.MutationEvents eventInterface);
    native public NavigationCompletedEvent createEvent(def.js.StringTypes.NavigationCompletedEvent eventInterface);
    native public NavigationEvent createEvent(def.js.StringTypes.NavigationEvent eventInterface);
    native public NavigationEventWithReferrer createEvent(def.js.StringTypes.NavigationEventWithReferrer eventInterface);
    native public OfflineAudioCompletionEvent createEvent(def.js.StringTypes.OfflineAudioCompletionEvent eventInterface);
    native public PageTransitionEvent createEvent(def.js.StringTypes.PageTransitionEvent eventInterface);
    native public PermissionRequestedEvent createEvent(def.js.StringTypes.PermissionRequestedEvent eventInterface);
    native public PointerEvent createEvent(def.js.StringTypes.PointerEvent eventInterface);
    native public PopStateEvent createEvent(def.js.StringTypes.PopStateEvent eventInterface);
    native public ProgressEvent createEvent(def.js.StringTypes.ProgressEvent eventInterface);
    native public SVGZoomEvent createEvent(def.js.StringTypes.SVGZoomEvent eventInterface);
    native public SVGZoomEvent createEvent(def.js.StringTypes.SVGZoomEvents eventInterface);
    native public ScriptNotifyEvent createEvent(def.js.StringTypes.ScriptNotifyEvent eventInterface);
    native public StorageEvent createEvent(def.js.StringTypes.StorageEvent eventInterface);
    native public TextEvent createEvent(def.js.StringTypes.TextEvent eventInterface);
    native public TouchEvent createEvent(def.js.StringTypes.TouchEvent eventInterface);
    native public TrackEvent createEvent(def.js.StringTypes.TrackEvent eventInterface);
    native public TransitionEvent createEvent(def.js.StringTypes.TransitionEvent eventInterface);
    native public UIEvent createEvent(def.js.StringTypes.UIEvent eventInterface);
    native public UIEvent createEvent(def.js.StringTypes.UIEvents eventInterface);
    native public UnviewableContentIdentifiedEvent createEvent(def.js.StringTypes.UnviewableContentIdentifiedEvent eventInterface);
    native public WebGLContextEvent createEvent(def.js.StringTypes.WebGLContextEvent eventInterface);
    native public WheelEvent createEvent(def.js.StringTypes.WheelEvent eventInterface);
    native public Event createEvent(java.lang.String eventInterface);
}

