package def.dom;

import def.js.StringTypes;
import def.js.StringTypes.*;

@jsweet.lang.Extends({GlobalEventHandlers.class,ElementTraversal.class,NodeSelector.class,ChildNode.class})
public class Element extends Node {
    public DOMTokenList classList;
    public double clientHeight;
    public double clientLeft;
    public double clientTop;
    public double clientWidth;
    public double msContentZoomFactor;
    public java.lang.String msRegionOverflow;
    public java.util.function.Function<AriaRequestEvent,java.lang.Object> onariarequest;
    public java.util.function.Function<CommandEvent,java.lang.Object> oncommand;
    public java.util.function.Function<PointerEvent,java.lang.Object> ongotpointercapture;
    public java.util.function.Function<PointerEvent,java.lang.Object> onlostpointercapture;
    public java.util.function.Function<MSGestureEvent,java.lang.Object> onmsgesturechange;
    public java.util.function.Function<MSGestureEvent,java.lang.Object> onmsgesturedoubletap;
    public java.util.function.Function<MSGestureEvent,java.lang.Object> onmsgestureend;
    public java.util.function.Function<MSGestureEvent,java.lang.Object> onmsgesturehold;
    public java.util.function.Function<MSGestureEvent,java.lang.Object> onmsgesturestart;
    public java.util.function.Function<MSGestureEvent,java.lang.Object> onmsgesturetap;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmsgotpointercapture;
    public java.util.function.Function<MSGestureEvent,java.lang.Object> onmsinertiastart;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmslostpointercapture;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmspointercancel;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmspointerdown;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmspointerenter;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmspointerleave;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmspointermove;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmspointerout;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmspointerover;
    public java.util.function.Function<MSPointerEvent,java.lang.Object> onmspointerup;
    public java.util.function.Function<TouchEvent,java.lang.Object> ontouchcancel;
    public java.util.function.Function<TouchEvent,java.lang.Object> ontouchend;
    public java.util.function.Function<TouchEvent,java.lang.Object> ontouchmove;
    public java.util.function.Function<TouchEvent,java.lang.Object> ontouchstart;
    public java.util.function.Function<Event,java.lang.Object> onwebkitfullscreenchange;
    public java.util.function.Function<Event,java.lang.Object> onwebkitfullscreenerror;
    public double scrollHeight;
    public double scrollLeft;
    public double scrollTop;
    public double scrollWidth;
    public java.lang.String tagName;
    native public java.lang.String getAttribute(java.lang.String name);
    native public java.lang.String getAttributeNS(java.lang.String namespaceURI, java.lang.String localName);
    native public Attr getAttributeNode(java.lang.String name);
    native public Attr getAttributeNodeNS(java.lang.String namespaceURI, java.lang.String localName);
    native public ClientRect getBoundingClientRect();
    native public ClientRectList getClientRects();
    native public NodeListOf<HTMLAnchorElement> getElementsByTagName(def.js.StringTypes.a name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.abbr name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.acronym name);
    native public NodeListOf<HTMLBlockElement> getElementsByTagName(def.js.StringTypes.address name);
    native public NodeListOf<HTMLAppletElement> getElementsByTagName(def.js.StringTypes.applet name);
    native public NodeListOf<HTMLAreaElement> getElementsByTagName(def.js.StringTypes.area name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.article name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.aside name);
    native public NodeListOf<HTMLAudioElement> getElementsByTagName(def.js.StringTypes.audio name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.b name);
    native public NodeListOf<HTMLBaseElement> getElementsByTagName(def.js.StringTypes.base name);
    native public NodeListOf<HTMLBaseFontElement> getElementsByTagName(def.js.StringTypes.basefont name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.bdo name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.big name);
    native public NodeListOf<HTMLBlockElement> getElementsByTagName(def.js.StringTypes.blockquote name);
    native public NodeListOf<HTMLBodyElement> getElementsByTagName(def.js.StringTypes.body name);
    native public NodeListOf<HTMLBRElement> getElementsByTagName(def.js.StringTypes.br name);
    native public NodeListOf<HTMLButtonElement> getElementsByTagName(def.js.StringTypes.button name);
    native public NodeListOf<HTMLCanvasElement> getElementsByTagName(def.js.StringTypes.canvas name);
    native public NodeListOf<HTMLTableCaptionElement> getElementsByTagName(def.js.StringTypes.caption name);
    native public NodeListOf<HTMLBlockElement> getElementsByTagName(def.js.StringTypes.center name);
    native public NodeListOf<SVGCircleElement> getElementsByTagName(def.js.StringTypes.circle name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.cite name);
    native public NodeListOf<SVGClipPathElement> getElementsByTagName(def.js.StringTypes.clippath name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.code name);
    native public NodeListOf<HTMLTableColElement> getElementsByTagName(def.js.StringTypes.col name);
    native public NodeListOf<HTMLTableColElement> getElementsByTagName(def.js.StringTypes.colgroup name);
    native public NodeListOf<HTMLDataListElement> getElementsByTagName(def.js.StringTypes.datalist name);
    native public NodeListOf<HTMLDDElement> getElementsByTagName(def.js.StringTypes.dd name);
    native public NodeListOf<SVGDefsElement> getElementsByTagName(def.js.StringTypes.defs name);
    native public NodeListOf<HTMLModElement> getElementsByTagName(def.js.StringTypes.del name);
    native public NodeListOf<SVGDescElement> getElementsByTagName(def.js.StringTypes.desc name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.dfn name);
    native public NodeListOf<HTMLDirectoryElement> getElementsByTagName(def.js.StringTypes.dir name);
    native public NodeListOf<HTMLDivElement> getElementsByTagName(def.js.StringTypes.div name);
    native public NodeListOf<HTMLDListElement> getElementsByTagName(def.js.StringTypes.dl name);
    native public NodeListOf<HTMLDTElement> getElementsByTagName(def.js.StringTypes.dt name);
    native public NodeListOf<SVGEllipseElement> getElementsByTagName(def.js.StringTypes.ellipse name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.em name);
    native public NodeListOf<HTMLEmbedElement> getElementsByTagName(def.js.StringTypes.embed name);
    native public NodeListOf<SVGFEBlendElement> getElementsByTagName(def.js.StringTypes.feblend name);
    native public NodeListOf<SVGFEColorMatrixElement> getElementsByTagName(def.js.StringTypes.fecolormatrix name);
    native public NodeListOf<SVGFEComponentTransferElement> getElementsByTagName(def.js.StringTypes.fecomponenttransfer name);
    native public NodeListOf<SVGFECompositeElement> getElementsByTagName(def.js.StringTypes.fecomposite name);
    native public NodeListOf<SVGFEConvolveMatrixElement> getElementsByTagName(def.js.StringTypes.feconvolvematrix name);
    native public NodeListOf<SVGFEDiffuseLightingElement> getElementsByTagName(def.js.StringTypes.fediffuselighting name);
    native public NodeListOf<SVGFEDisplacementMapElement> getElementsByTagName(def.js.StringTypes.fedisplacementmap name);
    native public NodeListOf<SVGFEDistantLightElement> getElementsByTagName(def.js.StringTypes.fedistantlight name);
    native public NodeListOf<SVGFEFloodElement> getElementsByTagName(def.js.StringTypes.feflood name);
    native public NodeListOf<SVGFEFuncAElement> getElementsByTagName(def.js.StringTypes.fefunca name);
    native public NodeListOf<SVGFEFuncBElement> getElementsByTagName(def.js.StringTypes.fefuncb name);
    native public NodeListOf<SVGFEFuncGElement> getElementsByTagName(def.js.StringTypes.fefuncg name);
    native public NodeListOf<SVGFEFuncRElement> getElementsByTagName(def.js.StringTypes.fefuncr name);
    native public NodeListOf<SVGFEGaussianBlurElement> getElementsByTagName(def.js.StringTypes.fegaussianblur name);
    native public NodeListOf<SVGFEImageElement> getElementsByTagName(def.js.StringTypes.feimage name);
    native public NodeListOf<SVGFEMergeElement> getElementsByTagName(def.js.StringTypes.femerge name);
    native public NodeListOf<SVGFEMergeNodeElement> getElementsByTagName(def.js.StringTypes.femergenode name);
    native public NodeListOf<SVGFEMorphologyElement> getElementsByTagName(def.js.StringTypes.femorphology name);
    native public NodeListOf<SVGFEOffsetElement> getElementsByTagName(def.js.StringTypes.feoffset name);
    native public NodeListOf<SVGFEPointLightElement> getElementsByTagName(def.js.StringTypes.fepointlight name);
    native public NodeListOf<SVGFESpecularLightingElement> getElementsByTagName(def.js.StringTypes.fespecularlighting name);
    native public NodeListOf<SVGFESpotLightElement> getElementsByTagName(def.js.StringTypes.fespotlight name);
    native public NodeListOf<SVGFETileElement> getElementsByTagName(def.js.StringTypes.fetile name);
    native public NodeListOf<SVGFETurbulenceElement> getElementsByTagName(def.js.StringTypes.feturbulence name);
    native public NodeListOf<HTMLFieldSetElement> getElementsByTagName(def.js.StringTypes.fieldset name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.figcaption name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.figure name);
    native public NodeListOf<SVGFilterElement> getElementsByTagName(def.js.StringTypes.filter name);
    native public NodeListOf<HTMLFontElement> getElementsByTagName(def.js.StringTypes.font name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.footer name);
    native public NodeListOf<SVGForeignObjectElement> getElementsByTagName(def.js.StringTypes.foreignobject name);
    native public NodeListOf<HTMLFormElement> getElementsByTagName(def.js.StringTypes.form name);
    native public NodeListOf<HTMLFrameElement> getElementsByTagName(def.js.StringTypes.frame name);
    native public NodeListOf<HTMLFrameSetElement> getElementsByTagName(def.js.StringTypes.frameset name);
    native public NodeListOf<SVGGElement> getElementsByTagName(def.js.StringTypes.g name);
    native public NodeListOf<HTMLHeadingElement> getElementsByTagName(def.js.StringTypes.h1 name);
    native public NodeListOf<HTMLHeadingElement> getElementsByTagName(def.js.StringTypes.h2 name);
    native public NodeListOf<HTMLHeadingElement> getElementsByTagName(def.js.StringTypes.h3 name);
    native public NodeListOf<HTMLHeadingElement> getElementsByTagName(def.js.StringTypes.h4 name);
    native public NodeListOf<HTMLHeadingElement> getElementsByTagName(def.js.StringTypes.h5 name);
    native public NodeListOf<HTMLHeadingElement> getElementsByTagName(def.js.StringTypes.h6 name);
    native public NodeListOf<HTMLHeadElement> getElementsByTagName(def.js.StringTypes.head name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.header name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.hgroup name);
    native public NodeListOf<HTMLHRElement> getElementsByTagName(def.js.StringTypes.hr name);
    native public NodeListOf<HTMLHtmlElement> getElementsByTagName(def.js.StringTypes.html name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.i name);
    native public NodeListOf<HTMLIFrameElement> getElementsByTagName(def.js.StringTypes.iframe name);
    native public NodeListOf<SVGImageElement> getElementsByTagName(def.js.StringTypes.image name);
    native public NodeListOf<HTMLImageElement> getElementsByTagName(def.js.StringTypes.img name);
    native public NodeListOf<HTMLInputElement> getElementsByTagName(def.js.StringTypes.input name);
    native public NodeListOf<HTMLModElement> getElementsByTagName(def.js.StringTypes.ins name);
    native public NodeListOf<HTMLIsIndexElement> getElementsByTagName(def.js.StringTypes.isindex name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.kbd name);
    native public NodeListOf<HTMLBlockElement> getElementsByTagName(def.js.StringTypes.keygen name);
    native public NodeListOf<HTMLLabelElement> getElementsByTagName(def.js.StringTypes.label name);
    native public NodeListOf<HTMLLegendElement> getElementsByTagName(def.js.StringTypes.legend name);
    native public NodeListOf<HTMLLIElement> getElementsByTagName(def.js.StringTypes.li name);
    native public NodeListOf<SVGLineElement> getElementsByTagName(def.js.StringTypes.line name);
    native public NodeListOf<SVGLinearGradientElement> getElementsByTagName(def.js.StringTypes.lineargradient name);
    native public NodeListOf<HTMLLinkElement> getElementsByTagName(def.js.StringTypes.link name);
    native public NodeListOf<HTMLBlockElement> getElementsByTagName(def.js.StringTypes.listing name);
    native public NodeListOf<HTMLMapElement> getElementsByTagName(def.js.StringTypes.map name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.mark name);
    native public NodeListOf<SVGMarkerElement> getElementsByTagName(def.js.StringTypes.marker name);
    native public NodeListOf<HTMLMarqueeElement> getElementsByTagName(def.js.StringTypes.marquee name);
    native public NodeListOf<SVGMaskElement> getElementsByTagName(def.js.StringTypes.mask name);
    native public NodeListOf<HTMLMenuElement> getElementsByTagName(def.js.StringTypes.menu name);
    native public NodeListOf<HTMLMetaElement> getElementsByTagName(def.js.StringTypes.meta name);
    native public NodeListOf<SVGMetadataElement> getElementsByTagName(def.js.StringTypes.metadata name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.nav name);
    native public NodeListOf<HTMLNextIdElement> getElementsByTagName(def.js.StringTypes.nextid name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.nobr name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.noframes name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.noscript name);
    native public NodeListOf<HTMLObjectElement> getElementsByTagName(def.js.StringTypes.object name);
    native public NodeListOf<HTMLOListElement> getElementsByTagName(def.js.StringTypes.ol name);
    native public NodeListOf<HTMLOptGroupElement> getElementsByTagName(def.js.StringTypes.optgroup name);
    native public NodeListOf<HTMLOptionElement> getElementsByTagName(def.js.StringTypes.option name);
    native public NodeListOf<HTMLParagraphElement> getElementsByTagName(def.js.StringTypes.p name);
    native public NodeListOf<HTMLParamElement> getElementsByTagName(def.js.StringTypes.param name);
    native public NodeListOf<SVGPathElement> getElementsByTagName(def.js.StringTypes.path name);
    native public NodeListOf<SVGPatternElement> getElementsByTagName(def.js.StringTypes.pattern name);
    native public NodeListOf<HTMLBlockElement> getElementsByTagName(def.js.StringTypes.plaintext name);
    native public NodeListOf<SVGPolygonElement> getElementsByTagName(def.js.StringTypes.polygon name);
    native public NodeListOf<SVGPolylineElement> getElementsByTagName(def.js.StringTypes.polyline name);
    native public NodeListOf<HTMLPreElement> getElementsByTagName(def.js.StringTypes.pre name);
    native public NodeListOf<HTMLProgressElement> getElementsByTagName(def.js.StringTypes.progress name);
    native public NodeListOf<HTMLQuoteElement> getElementsByTagName(def.js.StringTypes.q name);
    native public NodeListOf<SVGRadialGradientElement> getElementsByTagName(def.js.StringTypes.radialgradient name);
    native public NodeListOf<SVGRectElement> getElementsByTagName(def.js.StringTypes.rect name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.rt name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.ruby name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.s name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.samp name);
    native public NodeListOf<HTMLScriptElement> getElementsByTagName(def.js.StringTypes.script name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.section name);
    native public NodeListOf<HTMLSelectElement> getElementsByTagName(def.js.StringTypes.select name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.small name);
    native public NodeListOf<HTMLSourceElement> getElementsByTagName(def.js.StringTypes.source name);
    native public NodeListOf<HTMLSpanElement> getElementsByTagName(def.js.StringTypes.span name);
    native public NodeListOf<SVGStopElement> getElementsByTagName(def.js.StringTypes.stop name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.strike name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.strong name);
    native public NodeListOf<HTMLStyleElement> getElementsByTagName(def.js.StringTypes.style name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.sub name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.sup name);
    native public NodeListOf<SVGSVGElement> getElementsByTagName(def.js.StringTypes.svg name);
    native public NodeListOf<SVGSwitchElement> getElementsByTagName(def.js.StringTypes.Switch name);
    native public NodeListOf<SVGSymbolElement> getElementsByTagName(def.js.StringTypes.symbol name);
    native public NodeListOf<HTMLTableElement> getElementsByTagName(def.js.StringTypes.table name);
    native public NodeListOf<HTMLTableSectionElement> getElementsByTagName(def.js.StringTypes.tbody name);
    native public NodeListOf<HTMLTableDataCellElement> getElementsByTagName(def.js.StringTypes.td name);
    native public NodeListOf<SVGTextElement> getElementsByTagName(def.js.StringTypes.text name);
    native public NodeListOf<SVGTextPathElement> getElementsByTagName(def.js.StringTypes.textpath name);
    native public NodeListOf<HTMLTextAreaElement> getElementsByTagName(def.js.StringTypes.textarea name);
    native public NodeListOf<HTMLTableSectionElement> getElementsByTagName(def.js.StringTypes.tfoot name);
    native public NodeListOf<HTMLTableHeaderCellElement> getElementsByTagName(def.js.StringTypes.th name);
    native public NodeListOf<HTMLTableSectionElement> getElementsByTagName(def.js.StringTypes.thead name);
    native public NodeListOf<HTMLTitleElement> getElementsByTagName(def.js.StringTypes.title name);
    native public NodeListOf<HTMLTableRowElement> getElementsByTagName(def.js.StringTypes.tr name);
    native public NodeListOf<HTMLTrackElement> getElementsByTagName(def.js.StringTypes.track name);
    native public NodeListOf<SVGTSpanElement> getElementsByTagName(def.js.StringTypes.tspan name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.tt name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.u name);
    native public NodeListOf<HTMLUListElement> getElementsByTagName(def.js.StringTypes.ul name);
    native public NodeListOf<SVGUseElement> getElementsByTagName(def.js.StringTypes.use name);
    native public NodeListOf<HTMLPhraseElement> getElementsByTagName(def.js.StringTypes.var name);
    native public NodeListOf<HTMLVideoElement> getElementsByTagName(def.js.StringTypes.video name);
    native public NodeListOf<SVGViewElement> getElementsByTagName(def.js.StringTypes.view name);
    native public NodeListOf<HTMLElement> getElementsByTagName(def.js.StringTypes.wbr name);
    native public NodeListOf<MSHTMLWebViewElement> getElementsByTagName(def.js.StringTypes.x_ms_webview name);
    native public NodeListOf<HTMLBlockElement> getElementsByTagName(def.js.StringTypes.xmp name);
    native public NodeList getElementsByTagName(java.lang.String name);
    native public NodeList getElementsByTagNameNS(java.lang.String namespaceURI, java.lang.String localName);
    native public java.lang.Boolean hasAttribute(java.lang.String name);
    native public java.lang.Boolean hasAttributeNS(java.lang.String namespaceURI, java.lang.String localName);
    native public MSRangeCollection msGetRegionContent();
    native public ClientRect msGetUntransformedBounds();
    native public java.lang.Boolean msMatchesSelector(java.lang.String selectors);
    native public void msReleasePointerCapture(double pointerId);
    native public void msSetPointerCapture(double pointerId);
    native public void msZoomTo(MsZoomToOptions args);
    native public void releasePointerCapture(double pointerId);
    native public void removeAttribute(java.lang.String name);
    native public void removeAttributeNS(java.lang.String namespaceURI, java.lang.String localName);
    native public Attr removeAttributeNode(Attr oldAttr);
    native public void requestFullscreen();
    native public void requestPointerLock();
    native public void setAttribute(java.lang.String name, java.lang.String value);
    native public void setAttributeNS(java.lang.String namespaceURI, java.lang.String qualifiedName, java.lang.String value);
    native public Attr setAttributeNode(Attr newAttr);
    native public Attr setAttributeNodeNS(Attr newAttr);
    native public void setPointerCapture(double pointerId);
    native public java.lang.Boolean webkitMatchesSelector(java.lang.String selectors);
    native public void webkitRequestFullScreen();
    native public void webkitRequestFullscreen();
    native public void addEventListener(def.js.StringTypes.MSGestureChange type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSGestureDoubleTap type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSGestureEnd type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSGestureHold type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSGestureStart type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSGestureTap type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSGotPointerCapture type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSInertiaStart type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSLostPointerCapture type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSPointerCancel type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSPointerDown type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSPointerEnter type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSPointerLeave type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSPointerMove type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSPointerOut type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSPointerOver type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.MSPointerUp type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.ariarequest type, java.util.function.Function<AriaRequestEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.command type, java.util.function.Function<CommandEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.gotpointercapture type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.lostpointercapture type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.touchcancel type, java.util.function.Function<TouchEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.touchend type, java.util.function.Function<TouchEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.touchmove type, java.util.function.Function<TouchEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.touchstart type, java.util.function.Function<TouchEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.webkitfullscreenchange type, java.util.function.Function<Event,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.webkitfullscreenerror type, java.util.function.Function<Event,java.lang.Object> listener, java.lang.Boolean useCapture);
    public static Element prototype;
    public Element(){}
    public java.util.function.Function<PointerEvent,java.lang.Object> onpointercancel;
    public java.util.function.Function<PointerEvent,java.lang.Object> onpointerdown;
    public java.util.function.Function<PointerEvent,java.lang.Object> onpointerenter;
    public java.util.function.Function<PointerEvent,java.lang.Object> onpointerleave;
    public java.util.function.Function<PointerEvent,java.lang.Object> onpointermove;
    public java.util.function.Function<PointerEvent,java.lang.Object> onpointerout;
    public java.util.function.Function<PointerEvent,java.lang.Object> onpointerover;
    public java.util.function.Function<PointerEvent,java.lang.Object> onpointerup;
    public java.util.function.Function<WheelEvent,java.lang.Object> onwheel;
    native public void addEventListener(def.js.StringTypes.pointercancel type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.pointerdown type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.pointerenter type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.pointerleave type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.pointermove type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.pointerout type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.pointerover type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.pointerup type, java.util.function.Function<PointerEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(def.js.StringTypes.wheel type, java.util.function.Function<WheelEvent,java.lang.Object> listener, java.lang.Boolean useCapture);
    native public void addEventListener(java.lang.String type, EventListener listener, java.lang.Boolean useCapture);
    public double childElementCount;
    public Element firstElementChild;
    public Element lastElementChild;
    public Element nextElementSibling;
    public Element previousElementSibling;
    native public Element querySelector(java.lang.String selectors);
    native public NodeList querySelectorAll(java.lang.String selectors);
    native public void remove();
    native public java.lang.String getAttribute();
    native public void removeAttribute();
    native public void setAttribute(java.lang.String name);
    native public void setAttribute();
    native public void addEventListener(def.js.StringTypes.MSGestureChange type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSGestureDoubleTap type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSGestureEnd type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSGestureHold type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSGestureStart type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSGestureTap type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSGotPointerCapture type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSInertiaStart type, java.util.function.Function<MSGestureEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSLostPointerCapture type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSPointerCancel type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSPointerDown type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSPointerEnter type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSPointerLeave type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSPointerMove type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSPointerOut type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSPointerOver type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.MSPointerUp type, java.util.function.Function<MSPointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.ariarequest type, java.util.function.Function<AriaRequestEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.command type, java.util.function.Function<CommandEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.gotpointercapture type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.lostpointercapture type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.pointercancel type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.pointerdown type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.pointerenter type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.pointerleave type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.pointermove type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.pointerout type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.pointerover type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.pointerup type, java.util.function.Function<PointerEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.touchcancel type, java.util.function.Function<TouchEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.touchend type, java.util.function.Function<TouchEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.touchmove type, java.util.function.Function<TouchEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.touchstart type, java.util.function.Function<TouchEvent,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.webkitfullscreenchange type, java.util.function.Function<Event,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.webkitfullscreenerror type, java.util.function.Function<Event,java.lang.Object> listener);
    native public void addEventListener(def.js.StringTypes.wheel type, java.util.function.Function<WheelEvent,java.lang.Object> listener);
    native public void addEventListener(java.lang.String type, EventListener listener);
    native public void addEventListener(java.lang.String type, EventListenerObject listener, java.lang.Boolean useCapture);
    native public void addEventListener(java.lang.String type, EventListenerObject listener);
}

