package def.dom;
/** This class holds all the global functions and variables of the jsweet.dom package. */
public final class Globals extends def.js.Object {
    private Globals(){}
    public static Audio Audio;
    public static Image Image;
    public static Option Option;
    public static double animationStartTime;
    public static ApplicationCache applicationCache;
    public static Navigator clientInformation;
    public static Boolean closed;
    public static Crypto crypto;
    public static String defaultStatus;
    public static double devicePixelRatio;
    public static String doNotTrack;
    public static Document document;
    public static Event event;
    public static External external;
    public static Element frameElement;
    public static Window frames;
    public static History history;
    public static double innerHeight;
    public static double innerWidth;
    public static double length;
    public static Location location;
    public static BarProp locationbar;
    public static BarProp menubar;
    public static double msAnimationStartTime;
    public static String name;
    public static Navigator navigator;
    public static jsweet.util.union.Union<String,Boolean> offscreenBuffering;
    public static java.util.function.Function<Event,Object> onabort;
    public static java.util.function.Function<Event,Object> onafterprint;
    public static java.util.function.Function<Event,Object> onbeforeprint;
    public static java.util.function.Function<BeforeUnloadEvent,Object> onbeforeunload;
    public static java.util.function.Function<FocusEvent,Object> onblur;
    public static java.util.function.Function<Event,Object> oncanplay;
    public static java.util.function.Function<Event,Object> oncanplaythrough;
    public static java.util.function.Function<Event,Object> onchange;
    public static java.util.function.Function<MouseEvent,Object> onclick;
    public static java.util.function.Function<Event,Object> oncompassneedscalibration;
    public static java.util.function.Function<PointerEvent,Object> oncontextmenu;
    public static java.util.function.Function<MouseEvent,Object> ondblclick;
    public static java.util.function.Function<DeviceMotionEvent,Object> ondevicemotion;
    public static java.util.function.Function<DeviceOrientationEvent,Object> ondeviceorientation;
    public static java.util.function.Function<DragEvent,Object> ondrag;
    public static java.util.function.Function<DragEvent,Object> ondragend;
    public static java.util.function.Function<DragEvent,Object> ondragenter;
    public static java.util.function.Function<DragEvent,Object> ondragleave;
    public static java.util.function.Function<DragEvent,Object> ondragover;
    public static java.util.function.Function<DragEvent,Object> ondragstart;
    public static java.util.function.Function<DragEvent,Object> ondrop;
    public static java.util.function.Function<Event,Object> ondurationchange;
    public static java.util.function.Function<Event,Object> onemptied;
    public static java.util.function.Function<Event,Object> onended;
    public static ErrorEventHandler onerror;
    public static java.util.function.Function<FocusEvent,Object> onfocus;
    public static java.util.function.Function<HashChangeEvent,Object> onhashchange;
    public static java.util.function.Function<Event,Object> oninput;
    public static java.util.function.Function<KeyboardEvent,Object> onkeydown;
    public static java.util.function.Function<KeyboardEvent,Object> onkeypress;
    public static java.util.function.Function<KeyboardEvent,Object> onkeyup;
    public static java.util.function.Function<Event,Object> onload;
    public static java.util.function.Function<Event,Object> onloadeddata;
    public static java.util.function.Function<Event,Object> onloadedmetadata;
    public static java.util.function.Function<Event,Object> onloadstart;
    public static java.util.function.Function<MessageEvent,Object> onmessage;
    public static java.util.function.Function<MouseEvent,Object> onmousedown;
    public static java.util.function.Function<MouseEvent,Object> onmouseenter;
    public static java.util.function.Function<MouseEvent,Object> onmouseleave;
    public static java.util.function.Function<MouseEvent,Object> onmousemove;
    public static java.util.function.Function<MouseEvent,Object> onmouseout;
    public static java.util.function.Function<MouseEvent,Object> onmouseover;
    public static java.util.function.Function<MouseEvent,Object> onmouseup;
    public static java.util.function.Function<MouseWheelEvent,Object> onmousewheel;
    public static java.util.function.Function<MSGestureEvent,Object> onmsgesturechange;
    public static java.util.function.Function<MSGestureEvent,Object> onmsgesturedoubletap;
    public static java.util.function.Function<MSGestureEvent,Object> onmsgestureend;
    public static java.util.function.Function<MSGestureEvent,Object> onmsgesturehold;
    public static java.util.function.Function<MSGestureEvent,Object> onmsgesturestart;
    public static java.util.function.Function<MSGestureEvent,Object> onmsgesturetap;
    public static java.util.function.Function<MSGestureEvent,Object> onmsinertiastart;
    public static java.util.function.Function<MSPointerEvent,Object> onmspointercancel;
    public static java.util.function.Function<MSPointerEvent,Object> onmspointerdown;
    public static java.util.function.Function<MSPointerEvent,Object> onmspointerenter;
    public static java.util.function.Function<MSPointerEvent,Object> onmspointerleave;
    public static java.util.function.Function<MSPointerEvent,Object> onmspointermove;
    public static java.util.function.Function<MSPointerEvent,Object> onmspointerout;
    public static java.util.function.Function<MSPointerEvent,Object> onmspointerover;
    public static java.util.function.Function<MSPointerEvent,Object> onmspointerup;
    public static java.util.function.Function<Event,Object> onoffline;
    public static java.util.function.Function<Event,Object> ononline;
    public static java.util.function.Function<Event,Object> onorientationchange;
    public static java.util.function.Function<PageTransitionEvent,Object> onpagehide;
    public static java.util.function.Function<PageTransitionEvent,Object> onpageshow;
    public static java.util.function.Function<Event,Object> onpause;
    public static java.util.function.Function<Event,Object> onplay;
    public static java.util.function.Function<Event,Object> onplaying;
    public static java.util.function.Function<PopStateEvent,Object> onpopstate;
    public static java.util.function.Function<ProgressEvent,Object> onprogress;
    public static java.util.function.Function<Event,Object> onratechange;
    public static java.util.function.Function<ProgressEvent,Object> onreadystatechange;
    public static java.util.function.Function<Event,Object> onreset;
    public static java.util.function.Function<UIEvent,Object> onresize;
    public static java.util.function.Function<UIEvent,Object> onscroll;
    public static java.util.function.Function<Event,Object> onseeked;
    public static java.util.function.Function<Event,Object> onseeking;
    public static java.util.function.Function<UIEvent,Object> onselect;
    public static java.util.function.Function<Event,Object> onstalled;
    public static java.util.function.Function<StorageEvent,Object> onstorage;
    public static java.util.function.Function<Event,Object> onsubmit;
    public static java.util.function.Function<Event,Object> onsuspend;
    public static java.util.function.Function<Event,Object> ontimeupdate;
    public static Object ontouchcancel;
    public static Object ontouchend;
    public static Object ontouchmove;
    public static Object ontouchstart;
    public static java.util.function.Function<Event,Object> onunload;
    public static java.util.function.Function<Event,Object> onvolumechange;
    public static java.util.function.Function<Event,Object> onwaiting;
    public static Window opener;
    public static jsweet.util.union.Union<String,Double> orientation;
    public static double outerHeight;
    public static double outerWidth;
    public static double pageXOffset;
    public static double pageYOffset;
    public static Window parent;
    public static Performance performance;
    public static BarProp personalbar;
    public static Screen screen;
    public static double screenLeft;
    public static double screenTop;
    public static double screenX;
    public static double screenY;
    public static double scrollX;
    public static double scrollY;
    public static BarProp scrollbars;
    public static Window self;
    public static String status;
    public static BarProp statusbar;
    public static StyleMedia styleMedia;
    public static BarProp toolbar;
    public static Window top;
    public static Window window;
    public static URL URL;
    native public static void alert(Object message);
    native public static void blur();
    native public static void cancelAnimationFrame(double handle);
    native public static void captureEvents();
    native public static void close();
    native public static Boolean confirm(String message);
    native public static void focus();
    native public static CSSStyleDeclaration getComputedStyle(Element elt, String pseudoElt);
    native public static CSSRuleList getMatchedCSSRules(Element elt, String pseudoElt);
    native public static Selection getSelection();
    native public static MediaQueryList matchMedia(String mediaQuery);
    native public static void moveBy(double x, double y);
    native public static void moveTo(double x, double y);
    native public static void msCancelRequestAnimationFrame(double handle);
    native public static MediaQueryList msMatchMedia(String mediaQuery);
    native public static double msRequestAnimationFrame(FrameRequestCallback callback);
    native public static void msWriteProfilerMark(String profilerMarkName);
    native public static Window open(String url, String target, String features, Boolean replace);
    native public static void postMessage(Object message, String targetOrigin, Object ports);
    native public static void print();
    native public static String prompt(String message, String _default);
    native public static void releaseEvents();
    native public static double requestAnimationFrame(FrameRequestCallback callback);
    native public static void resizeBy(double x, double y);
    native public static void resizeTo(double x, double y);
    native public static void scroll(double x, double y);
    native public static void scrollBy(double x, double y);
    native public static void scrollTo(double x, double y);
    native public static WebKitPoint webkitConvertPointFromNodeToPage(Node node, WebKitPoint pt);
    native public static WebKitPoint webkitConvertPointFromPageToNode(Node node, WebKitPoint pt);
    native public static String ToString();
    native public static Boolean dispatchEvent(Event evt);
    native public static void removeEventListener(String type, EventListener listener, Boolean useCapture);
    native public static void clearInterval(double handle);
    native public static void clearTimeout(double handle);
    native public static double setInterval(Object handler, Object timeout, Object... args);
    native public static double setTimeout(Object handler, Object timeout, Object... args);
    native public static void clearImmediate(double handle);
    native public static void msClearImmediate(double handle);
    native public static double msSetImmediate(Object expression, Object... args);
    native public static double setImmediate(Object expression, Object... args);
    public static Storage sessionStorage;
    public static Storage localStorage;
    public static Console console;
    public static java.util.function.Function<PointerEvent,Object> onpointercancel;
    public static java.util.function.Function<PointerEvent,Object> onpointerdown;
    public static java.util.function.Function<PointerEvent,Object> onpointerenter;
    public static java.util.function.Function<PointerEvent,Object> onpointerleave;
    public static java.util.function.Function<PointerEvent,Object> onpointermove;
    public static java.util.function.Function<PointerEvent,Object> onpointerout;
    public static java.util.function.Function<PointerEvent,Object> onpointerover;
    public static java.util.function.Function<PointerEvent,Object> onpointerup;
    public static java.util.function.Function<WheelEvent,Object> onwheel;
    public static IDBFactory indexedDB;
    public static IDBFactory msIndexedDB;
    native public static String atob(String encodedString);
    native public static String btoa(String rawString);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureChange type, java.util.function.Function<MSGestureEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureDoubleTap type, java.util.function.Function<MSGestureEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureEnd type, java.util.function.Function<MSGestureEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureHold type, java.util.function.Function<MSGestureEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureStart type, java.util.function.Function<MSGestureEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureTap type, java.util.function.Function<MSGestureEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSInertiaStart type, java.util.function.Function<MSGestureEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerCancel type, java.util.function.Function<MSPointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerDown type, java.util.function.Function<MSPointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerEnter type, java.util.function.Function<MSPointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerLeave type, java.util.function.Function<MSPointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerMove type, java.util.function.Function<MSPointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerOut type, java.util.function.Function<MSPointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerOver type, java.util.function.Function<MSPointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerUp type, java.util.function.Function<MSPointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.abort type, java.util.function.Function<UIEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.afterprint type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.beforeprint type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.beforeunload type, java.util.function.Function<BeforeUnloadEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.blur type, java.util.function.Function<FocusEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.canplay type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.canplaythrough type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.change type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.click type, java.util.function.Function<MouseEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.compassneedscalibration type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.contextmenu type, java.util.function.Function<PointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.dblclick type, java.util.function.Function<MouseEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.devicemotion type, java.util.function.Function<DeviceMotionEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.deviceorientation type, java.util.function.Function<DeviceOrientationEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.drag type, java.util.function.Function<DragEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.dragend type, java.util.function.Function<DragEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.dragenter type, java.util.function.Function<DragEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.dragleave type, java.util.function.Function<DragEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.dragover type, java.util.function.Function<DragEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.dragstart type, java.util.function.Function<DragEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.drop type, java.util.function.Function<DragEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.durationchange type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.emptied type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.ended type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.focus type, java.util.function.Function<FocusEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.hashchange type, java.util.function.Function<HashChangeEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.input type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.keydown type, java.util.function.Function<KeyboardEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.keypress type, java.util.function.Function<KeyboardEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.keyup type, java.util.function.Function<KeyboardEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.load type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.loadeddata type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.loadedmetadata type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.loadstart type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.message type, java.util.function.Function<MessageEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.mousedown type, java.util.function.Function<MouseEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.mouseenter type, java.util.function.Function<MouseEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.mouseleave type, java.util.function.Function<MouseEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.mousemove type, java.util.function.Function<MouseEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.mouseout type, java.util.function.Function<MouseEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.mouseover type, java.util.function.Function<MouseEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.mouseup type, java.util.function.Function<MouseEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.mousewheel type, java.util.function.Function<MouseWheelEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.offline type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.online type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.orientationchange type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pagehide type, java.util.function.Function<PageTransitionEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pageshow type, java.util.function.Function<PageTransitionEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pause type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.play type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.playing type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pointercancel type, java.util.function.Function<PointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pointerdown type, java.util.function.Function<PointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pointerenter type, java.util.function.Function<PointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pointerleave type, java.util.function.Function<PointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pointermove type, java.util.function.Function<PointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pointerout type, java.util.function.Function<PointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pointerover type, java.util.function.Function<PointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.pointerup type, java.util.function.Function<PointerEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.popstate type, java.util.function.Function<PopStateEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.progress type, java.util.function.Function<ProgressEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.ratechange type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.readystatechange type, java.util.function.Function<ProgressEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.reset type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.resize type, java.util.function.Function<UIEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.scroll type, java.util.function.Function<UIEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.seeked type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.seeking type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.select type, java.util.function.Function<UIEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.stalled type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.storage type, java.util.function.Function<StorageEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.submit type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.suspend type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.timeupdate type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.unload type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.volumechange type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.waiting type, java.util.function.Function<Event,Object> listener, Boolean useCapture);
    native public static void addEventListener(jsweet.util.StringTypes.wheel type, java.util.function.Function<WheelEvent,Object> listener, Boolean useCapture);
    native public static void addEventListener(String type, EventListener listener, Boolean useCapture);
    native public static void alert();
    native public static Boolean confirm();
    native public static CSSStyleDeclaration getComputedStyle(Element elt);
    native public static CSSRuleList getMatchedCSSRules(Element elt);
    native public static void moveBy(double x);
    native public static void moveBy();
    native public static void moveTo(double x);
    native public static void moveTo();
    native public static Window open(String url, String target, String features);
    native public static Window open(String url, String target);
    native public static Window open(String url);
    native public static Window open();
    native public static void postMessage(Object message, String targetOrigin);
    native public static String prompt(String message);
    native public static String prompt();
    native public static void resizeBy(double x);
    native public static void resizeBy();
    native public static void resizeTo(double x);
    native public static void resizeTo();
    native public static void scroll(double x);
    native public static void scroll();
    native public static void scrollBy(double x);
    native public static void scrollBy();
    native public static void scrollTo(double x);
    native public static void scrollTo();
    native public static void addEventListener(String type, EventListener listener);
    native public static void removeEventListener(String type, EventListener listener);
    native public static double setInterval(Object handler);
    native public static double setTimeout(Object handler);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureChange type, java.util.function.Function<MSGestureEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureDoubleTap type, java.util.function.Function<MSGestureEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureEnd type, java.util.function.Function<MSGestureEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureHold type, java.util.function.Function<MSGestureEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureStart type, java.util.function.Function<MSGestureEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSGestureTap type, java.util.function.Function<MSGestureEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSInertiaStart type, java.util.function.Function<MSGestureEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerCancel type, java.util.function.Function<MSPointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerDown type, java.util.function.Function<MSPointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerEnter type, java.util.function.Function<MSPointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerLeave type, java.util.function.Function<MSPointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerMove type, java.util.function.Function<MSPointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerOut type, java.util.function.Function<MSPointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerOver type, java.util.function.Function<MSPointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.MSPointerUp type, java.util.function.Function<MSPointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.abort type, java.util.function.Function<UIEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.afterprint type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.beforeprint type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.beforeunload type, java.util.function.Function<BeforeUnloadEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.blur type, java.util.function.Function<FocusEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.canplay type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.canplaythrough type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.change type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.click type, java.util.function.Function<MouseEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.compassneedscalibration type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.contextmenu type, java.util.function.Function<PointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.dblclick type, java.util.function.Function<MouseEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.devicemotion type, java.util.function.Function<DeviceMotionEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.deviceorientation type, java.util.function.Function<DeviceOrientationEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.drag type, java.util.function.Function<DragEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.dragend type, java.util.function.Function<DragEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.dragenter type, java.util.function.Function<DragEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.dragleave type, java.util.function.Function<DragEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.dragover type, java.util.function.Function<DragEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.dragstart type, java.util.function.Function<DragEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.drop type, java.util.function.Function<DragEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.durationchange type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.emptied type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.ended type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.focus type, java.util.function.Function<FocusEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.hashchange type, java.util.function.Function<HashChangeEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.input type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.keydown type, java.util.function.Function<KeyboardEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.keypress type, java.util.function.Function<KeyboardEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.keyup type, java.util.function.Function<KeyboardEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.load type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.loadeddata type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.loadedmetadata type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.loadstart type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.message type, java.util.function.Function<MessageEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.mousedown type, java.util.function.Function<MouseEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.mouseenter type, java.util.function.Function<MouseEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.mouseleave type, java.util.function.Function<MouseEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.mousemove type, java.util.function.Function<MouseEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.mouseout type, java.util.function.Function<MouseEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.mouseover type, java.util.function.Function<MouseEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.mouseup type, java.util.function.Function<MouseEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.mousewheel type, java.util.function.Function<MouseWheelEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.offline type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.online type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.orientationchange type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pagehide type, java.util.function.Function<PageTransitionEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pageshow type, java.util.function.Function<PageTransitionEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pause type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.play type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.playing type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pointercancel type, java.util.function.Function<PointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pointerdown type, java.util.function.Function<PointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pointerenter type, java.util.function.Function<PointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pointerleave type, java.util.function.Function<PointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pointermove type, java.util.function.Function<PointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pointerout type, java.util.function.Function<PointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pointerover type, java.util.function.Function<PointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.pointerup type, java.util.function.Function<PointerEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.popstate type, java.util.function.Function<PopStateEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.progress type, java.util.function.Function<ProgressEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.ratechange type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.readystatechange type, java.util.function.Function<ProgressEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.reset type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.resize type, java.util.function.Function<UIEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.scroll type, java.util.function.Function<UIEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.seeked type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.seeking type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.select type, java.util.function.Function<UIEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.stalled type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.storage type, java.util.function.Function<StorageEvent,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.submit type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.suspend type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.timeupdate type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.unload type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.volumechange type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.waiting type, java.util.function.Function<Event,Object> listener);
    native public static void addEventListener(jsweet.util.StringTypes.wheel type, java.util.function.Function<WheelEvent,Object> listener);
    native public static void removeEventListener(String type, EventListenerObject listener, Boolean useCapture);
    native public static void addEventListener(String type, EventListenerObject listener, Boolean useCapture);
    native public static void addEventListener(String type, EventListenerObject listener);
    native public static void removeEventListener(String type, EventListenerObject listener);
    native public static void onerror(java.lang.String message, java.lang.String filename, double lineno, double colno, def.js.Error error);
    native public static void onerror(java.lang.String message, java.lang.String filename, double lineno, double colno);
    native public static void onerror(java.lang.String message, java.lang.String filename, double lineno);
    native public static void onerror(java.lang.String message, java.lang.String filename);
    native public static void onerror(java.lang.String message);
}

