
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 30 17:36:39 CET 2016
//----------------------------------------------------

package org.jsweet.input.typescriptdef.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 37;
  public static final int AS = 69;
  public static final int IDENTIFIER = 43;
  public static final int FROM = 70;
  public static final int GT = 18;
  public static final int TYPEOF = 66;
  public static final int IMPLEMENTS = 63;
  public static final int CONST = 67;
  public static final int EXPORT = 47;
  public static final int DECLARE_MODULE = 54;
  public static final int SEMI = 7;
  public static final int DECLARE_FUNCTION = 55;
  public static final int ENUM = 71;
  public static final int LPAREN_FUNC = 73;
  public static final int SQUARE = 14;
  public static final int COMMA = 3;
  public static final int RPAREN = 9;
  public static final int LT = 15;
  public static final int ANDAND = 31;
  public static final int OROR = 30;
  public static final int DECLARE = 53;
  public static final int LPAREN = 8;
  public static final int PROTECTED = 50;
  public static final int FALSE = 42;
  public static final int NOT = 33;
  public static final int DOTDOTDOT = 6;
  public static final int LF = 72;
  public static final int TYPE_MACRO = 58;
  public static final int RCPAREN = 11;
  public static final int VAR = 61;
  public static final int NOTEQUALS = 21;
  public static final int LCPAREN = 10;
  public static final int DECLARE_ENUM = 57;
  public static final int NUM = 40;
  public static final int DOLLAR = 45;
  public static final int CLASS = 60;
  public static final int ABSTRACT = 52;
  public static final int TUBE = 34;
  public static final int TRUE = 41;
  public static final int MATCHES = 36;
  public static final int PLUS = 26;
  public static final int QUESTION = 44;
  public static final int EXTENDS = 62;
  public static final int ASSIGN = 19;
  public static final int INTERFACE = 59;
  public static final int RPAREN_FUNC = 74;
  public static final int DIV = 23;
  public static final int PUBLIC = 51;
  public static final int MULT = 22;
  public static final int DOTDOT = 5;
  public static final int DOT = 4;
  public static final int INT = 39;
  public static final int LTE = 16;
  public static final int REFERENCE = 29;
  public static final int EOF = 0;
  public static final int COL = 2;
  public static final int FUNCTION = 48;
  public static final int DOC = 28;
  public static final int IMPORT = 46;
  public static final int RSPAREN = 13;
  public static final int IS = 68;
  public static final int MINUS = 24;
  public static final int ARROW_RIGHT = 38;
  public static final int error = 1;
  public static final int GTE = 17;
  public static final int MINUSMINUS = 25;
  public static final int LSPAREN = 12;
  public static final int PLUSPLUS = 27;
  public static final int NEW = 64;
  public static final int DECLARE_CLASS = 56;
  public static final int AND = 32;
  public static final int PRIVATE = 49;
  public static final int IMPLIES = 35;
  public static final int STATIC = 65;
  public static final int EQUALS = 20;
}

